apiVersion: v1
kind: Namespace
metadata:
  name: policies
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: subscription-admin
  namespace: policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: subscription-admin
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: open-cluster-management:subscription-admin
                subjects:
                  - kind: User
                    apiGroup: rbac.authorization.k8s.io
                    name: kube:admin
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-subscription-admin
  namespace: policies
placementRef:
  name: placement-subscription-admin
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: subscription-admin
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-subscription-admin
  namespace: policies
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
          - local-cluster
